definitions:
  domain.ReqAddKeluarga:
    properties:
      jenis_kelamin:
        type: integer
      nama:
        type: string
      orang_tua:
        type: integer
    required:
    - nama
    type: object
  domain.ReqUpdateKeluarga:
    properties:
      id_keluarga:
        type: integer
      jenis_kelamin:
        type: integer
      nama:
        type: string
      orang_tua:
        type: integer
    required:
    - nama
    type: object
  model.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact:
    email: arditya@kekasi.co.id
    name: Arditya Kekasi
    url: http://www.kekasi.co.id
  description: Pattern Go RestAPI + Socket.io v2. with the same ports.
  license:
    name: YouTube KekasiGen
    url: https://kekasi.link/kekasigensub
  termsOfService: https://id.linkedin.com/public-profile/in/arditya-kekasi
  title: RestAPI & Socket.io v2
  version: "1.0"
paths:
  /keluarga/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Tambah Keluarga
        in: body
        name: Keluarga
        required: true
        schema:
          $ref: '#/definitions/domain.ReqAddKeluarga'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      tags:
      - Keluarga
  /keluarga/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: Ubah Keluarga
        in: body
        name: Keluarga
        required: true
        schema:
          $ref: '#/definitions/domain.ReqUpdateKeluarga'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      tags:
      - Keluarga
schemes:
- http
- https
swagger: "2.0"
